version: '3.7'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VER=25
        - ARCH=aarch64 # x86_64 or aarch64
    tty: true
    volumes:
      - ..:/apl
      - ../node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
