import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1769278113946 implements MigrationInterface {
    name = 'AutoGeneratedMigration1769278113946'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "password"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "password" character varying NOT NULL`);
    }

}
